christianhelle/refitter

.github/workflows/release.yml, README.md, src/Refitter.Core/ParameterExtractor.cs, test/ConsoleApp/Program.cs
The changes here add's the missing Query parameters support in the generated Refit interface
Endpoints that use query parameters will be generated like this:
```cs
[Get("/pet/findByStatus")]
Task<ICollection<Pet>> FindPetsByStatus([Query]Status? status);
[Get("/pet/findByTags")]
Task<ICollection<Pet>> FindPetsByTags([Query(CollectionFormat.Multi)]ICollection<string> tags);
```
This was verified using the Swagger Petstore v3 OpenAPI specifications and tested using the following code:
```cs
var client = RestService.For<ISwaggerPetstore>("https://petstore3.swagger.io/api/v3");
var pet = await client.GetPetById(2);
Console.WriteLine($"Name: {pet.Name}");
Console.WriteLine($"Category: {pet.Category.Name}");
Console.WriteLine($"Status: {pet.Status}");
var pets = await …
```
=> Fix missing support for Query Parameters

src/Refitter.Core/ParameterExtractor.cs
Example YAML:
```yaml
swagger: '2.0'
info:
title: Reference parameters
version: v0.0.1
paths:
'/orders/{orderId}/order-items/{orderItemId}':
parameters:
- $ref: '#/parameters/OrderId'
- $ref: '#/parameters/OrderItemId'
delete:
summary: Delete an order item
description: >-
This method allows to remove an order item from an order, by specifying
their ids.
responses:
"204":
description: No Content.
default:
description: Default response
schema:
$ref: '#/definitions/Error'
definitions:
Error:
type: object
properties:
message:
type: string
parameters:
OrderId:
name: orderId
in: path
description: Identifier of the order.
required: true
type: string
format: uuid
OrderItemId:
name: orderItemId
in: path
description: Identifier of the order item.
required: true
type: string
format: uuid
``` …
=> fix path parameters in parent

src/Refitter.Core/ParameterExtractor.cs
Refitter was creating anonymous types for endpoints I had that take multipart/form-data bodies.
=> Handle multipart/form-data parameters

.gitignore, .vscode/launch.json, .vscode/tasks.json, src/Refitter.Core/CSharpClientGeneratorFactory.cs, src/Refitter.Core/CustomCSharpClientGenerator.cs, src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs, src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/StringCasingExtensions.cs, test/OpenAPI/v3.0/IngramMicro.json, test/smoke-tests.ps1
Hi there,
I was having some issues with refitter so I've created a fix for them, I hope they're of some use.
Things I've changed are:
* Multiline descriptions show on new lines without being commented out
* Query string parameter names aren't being encoded safely, things like dashes and reserved keywords causing problems
* Client methods aren't being encoded safely, this pull request just deals with full stops, I couldn't see any way to leverage NSwag's encoding
* Properties with no names aren't generated correctly. This one is weird and might be a bit specific to the doc I'm generating from.
* Fixed the smoke-test.ps1 cleanup of generated files
* Added vscode files
* Added IngramMicro.json sample for smoke tests
=> Various name encoding fixes, fix multiline descriptions

.vscode/launch.json, README.md, src/Refitter.Tests/Refitter.Tests.csproj, src/Refitter/Refitter.csproj
There is really no reason behind why this project targetted .NET 7.0 so I'm lowering it to .NET 6.0 to ensure that developers that work with constraints that require them to only use LTS versions of .NET can also use Refitter
This change was requested by @kirides and resolves #17
=> Charge Target Framework to .NET 6.0 (LTS)

.github/workflows/release.yml, README.md, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/Program.cs
This builds upon the contributions from https://github.com/christianhelle/refitter/pull/24
=> Add --no-operation-headers CLI tool argument

src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Tests/Refitter.Tests.csproj, src/Refitter.Tests/Resources/EmbeddedResources.cs, src/Refitter.Tests/Resources/SampleOpenSpecifications.cs, src/Refitter.Tests/Resources/V2/SwaggerPetstoreWithDifferentHeaders.json, src/Refitter.Tests/Resources/V2/SwaggerPetstoreWithDifferentHeaders.yaml, src/Refitter.Tests/Resources/V3/SwaggerPetstoreWithDifferentHeaders.json, src/Refitter.Tests/Resources/V3/SwaggerPetstoreWithDifferentHeaders.yaml, src/Refitter.Tests/SwaggerPetstoreTests.cs
Fix for the following issue:
- #26
In `source\repos\refitter\src\Refitter.Core\ParameterExtractor.cs`
Before:
```csharp
if(settings.GenerateOperationHeaders)
{
headerParameters = operationModel.Parameters
.Where(p => p.Kind == OpenApiParameterKind.Header && p.IsHeader)
.Select(p => $"{JoinAttributes($"Header(\"{p.VariableName}\")", GetAliasAsAttribute(p))}{GetBodyParameterType(p)} {p.VariableName}")
.ToList();
}
```
After:
```csharp
if(settings.GenerateOperationHeaders)
{
headerParameters = operationModel.Parameters
.Where(p => p.Kind == OpenApiParameterKind.Header && p.IsHeader)
.Select(p => $"{JoinAttributes($"Header(\"{p.Name}\")")}{GetBodyParameterType(p)} {p.VariableName}")
.ToList();
}
```
=> Fix for #26

src/Refitter/GenerateCommand.cs
Replaces all newline sequences in the generated code with [`Environment.NewLine`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.newline?view=net-6.0#system-environment-newline) using [`String.ReplaceLineEndings()`](https://learn.microsoft.com/en-us/dotnet/api/system.string.replacelineendings?view=net-6.0#system-string-replacelineendings) on the generated code
This resolves #57
=> Fix inconsistent line endings in generated file

.gitignore, src/.vscode/settings.json, src/Refitter.Core/OperationNameGenerator.cs, src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Tests/MultiPartFormDataTests.cs
The changes here adds support for `multipart/form-data` requests with a binary body. This is done by adding the `[Multipart]` attribute to the generated method and using `StreamPart` for the request body
The following OpenAPI v3 specifications
```json
{
"openapi":"3.0.2",
"paths":{
"/foo/{id}/files":{
"post":{
"summary":"uploads a file",
"operationId":"uploadFile",
"parameters":[
{
"name":"id",
"in":"path",
"description":"Id of the foo resource",
"required":true,
"schema":{
"type":"integer",
"format":"int64"
}
}
],
"requestBody":{
"content":{
"multipart/form-data":{
"schema":{
"type":"object",
"properties":{
"formFile":{
"type":"string",
"format":"binary"
}
}
},
"encoding":{
"formFile":{
"style":"form"
}
}
}
}
},
"responses":{
"200":{
"description":"successful operation"
}
}
}
}
}
}
``` …
=> Add support for multipart/form-data file uploads

src/Refitter.Core/RefitInterfaceGenerator.cs
Enhanced HTTP status code handling for API responses
Previously, our API handling logic only checked for a '200' HTTP status code to retrieve the response schema. However, there are several other success status codes, like '201', '203', and '206', which also indicate that the request was successful and can include a response schema.
https://restfulapi.net/http-status-codes/#2xx
=> Enhanced HTTP status code 200 handling for API responses

.github/workflows/template.yml, README.md, src/Refitter.Core/RefitGenerator.cs, src/Refitter.Core/RefitGeneratorSettings.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Core/StringSuffixUtils.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/MultipleInterfaceByTagGeneratorTests.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/MultipleInterfaceGeneratorTests.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/SingleInterfaceGeneratorTest.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreMultipleInterfacesByTag.refitter, src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreSingleInterface.refitter, src/Refitter.SourceGenerator.Tests/Refitter.SourceGenerator.Tests.csproj, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/Settings.cs, src/Refitter/SupportInformation.cs, test/smoke-tests.ps1
This PR adds an additional mode for `--multiple-interfaces` called `ByTag` which uses the first Tag of the operation to generate the interface name.
This PR also adds a `BREAKING` change as `--multiple-interfaces` now takes in an enumeration of `Unset`, `ByEndpoint` and `ByTag`.
The source generator `.refitter` file has the same breaking change, as it now takes its value as string like this:
```json
{
"multipleInterfaces": "ByTag" // or ByEndpoint
}
```
Generated sample:
```cs
namespace GeneratedCode
{
// No/Empty first Tag 
public interface IDocumentV1Api
{
[Get("/api/greet-unsafe")]
Task GreetUnsafe([Query] string name);
}
// tag "Greeting"
public interface IGreetingApi
{
[Get("/api/greet")]
Task Greet([Query] string name);
}
// tag "OpenApi"
public interface IOpenApiApi
{ …
```
=> Generate Multiple interfaces based on first Tag

.github/workflows/sonar-cloud.yml, README.md
Add Github Action workflow for SonarCloud analysis and add a quality gate badge to the README
=> Enable SonarCloud

.github/workflows/sonar-cloud.yml, README.md, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Core/WellKnownNamesspaces.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreMultipleInterfaces.refitter, src/Refitter.SourceGenerator.Tests/AdditionalFiles/SwaggerPetstoreMultipleInterfacesByTag.refitter, src/Refitter.Tests/SwaggerPetstoreTests.cs
This fixes a small issue introduced in #108 where a condition was missing that caused the `[Headers("Accept")]` to always be generated, regardless of what the `RefitGeneratorSettings` is configured to
=> Fix issue where [Headers("Accept")] is always generated

.github/workflows/build.yml, .github/workflows/codecov.yml, .gitignore, README.md
Public Codecov project:
https://app.codecov.io/gh/christianhelle/refitter
=> Add Codecov workflow and badge

.github/workflows/codecov.yml, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfacesByTag.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs, src/Refitter.Tests/Examples/MultipleInterfacesByEndpointTests.cs, src/Refitter.Tests/Examples/MultipleInterfacesByTagsTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs
The changes here add the `[GeneratedCode]` attribute to the generated types
=> Exclude from generated code from code coverage

.github/workflows/build.yml, src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Tests/Examples/CaseSensitiveParametersTests.cs
The changes here fixes a case sensitivity issue regarding handling query string parameters.
This resolves #124 
The follow OpenAPI spec:
```yaml
openapi: '3.0.0'
paths:
/job/{Id}:
post:
tags:
- 'Jobs'
operationId: 'Update job details'
description: 'Update the details of the specified job.'
parameters:
- in: 'path'
name: 'Id'
description: 'Foo Id'
required: true
schema:
type: 'string'
- in: 'query'
name: 'Title'
description: 'Job title'
required: true
schema:
type: 'string'
- in: 'query'
name: 'Description'
description: 'Job description'
required: true
schema:
type: 'string'
responses:
'200':
description: 'successful operation'
```
Generates the following:
```cs
[Post("/job/{Id}")]
Task UpdateJobDetails(
[AliasAs("Id")] string id, 
[Query, AliasAs("Title")] string title, 
[Query, …
```
=> Fix parameters' casing in openAPI document are not honoured in Refit interface methods

src/Refitter.Core/RefitGenerator.cs, src/Refitter.Core/RefitGeneratorSettings.cs, src/Refitter.Tests/Examples/FilterByPathTests.cs, src/Refitter.Tests/Examples/FilterByTagsTests.cs, src/Refitter/GenerateCommand.cs, src/Refitter/Settings.cs
This PR demonstrates how #131 could be implemented
It add `--match-path` and `--tag` CLI options, which allow the user to filter endpoints based on existing Tags and/or if the Path matches an regular expression.
It's not as fine grained as for supporting HTTP methods. I.e. you can't filter for `^/greet` and only allow `GET` and `PUT` or something like that.
A call might look like this:
```sh
refitter.exe swagger.json --tag Greeting --tag OpenApi --match-path '^/api/'
```
It works by modifying the OpenApiDocument and removing the Paths/Methods that don't match any of the Tags or patterns, thus further steps in code generation only see the filtered document.
=> Feature: Filtering of endpoints and tags

src/Refitter.Core/OpenApiDocumentFactory.cs, src/Refitter.Core/RefitGenerator.cs, src/Refitter.Tests/OpenApiDocumentFactoryTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter.Tests/TestFile.cs
The changes here introduces the `OpenApiDocumentFactory` as to handle URLs to OpenAPI specifications that return GZIP encoded streams.
=> Fix issue when downloading an OpenAPI spec from a URL that returns a GZIP stream

src/Refitter/Program.cs
A conditional statement was added in Program.cs to automatically insert `--help` as the default argument for the command app if no argument is provided by the user. This change simplifies the usability for those unfamiliar with the required command line arguments.
=> Show help text if no arguments are passed

README.md, src/Refitter/GenerateCommand.cs, src/Refitter/README.md, src/Refitter/Refitter.csproj, src/Refitter/Settings.cs, src/Refitter/Validation/OpenApiStats.cs, src/Refitter/Validation/OpenApiValidationException.cs, src/Refitter/Validation/OpenApiValidationResult.cs, src/Refitter/Validation/OpenApiValidator.cs
The changes here implement OpenAPI validation using Microsoft OpenAPI libraries. With the changes here, Refitter will print out validation errors (in red) and warnings (in yellow).
A user can also choose to opt out of OpenAPI validation by using the `--skip-validation` CLI tool argument
This pull request also includes a new feature that prints out OpenAPI specification statistics for the number of operations, links, parameters, requests, responses, etc...
It looks something like this:
```
OpenAPI document statistics:
- Path Items: 13
- Operations: 19
- Parameters: 17
- Request Bodies: 9
- Responses: 19
- Links: 0
- Callbacks: 0
- Schemas: 73
```
=> Introduce OpenAPI validation

src/Refitter.Core/RefitGenerator.cs, src/Refitter.Tests/Examples/FilterByTagsTests.cs
fixes #142 by changing includeTags filtering and restoring collection snapshots.
exclusion is now defined in a single statement, instead of a loop, to reduce likelyhood of failures.
Fixes improper use of collection enumeration and mutation while doing so.
We may not use code like the following, as that may either crash or produce UB.
```
foreach (var x in collection.Where(x....))
{
// NOT OK
collection.Remove(y);
}
```
instead, every mutating operation on a collection should enumerate on a snapshot
```
foreach (var x in collection.Where(x....).ToArray())
{
// OK
collection.Remove(y);
}
```
=> Fix #142 by changing includeTags filtering and restoring collection snapshots

README.md, src/Refitter.SourceGenerator/README.md
New "matchPath" fields have been added to the configuration examples in both Refitter.SourceGenerator's README file and the main project README. This enables the use of regular expressions to include only specific paths, providing additional flexibility for users.
=> Add matchPath option in example .refitter file in README

src/Refitter/Analytics.cs
The changes here improved the code readability and maintainability in the `Analytics` class by extracting the conditions used for determining if a feature can be logged from the iteration over Settings properties into a separate `CanLogFeature()` method. This change was necessary to clean up complex conditionals and also prepare the code for any future conditions that might be added for validating a loggable feature.
=> Skip default values when collecting feature usages for Analytics

src/Refitter/GenerateCommand.cs, src/Refitter/Program.cs
Moved the line that configures Analytics from the Main method of the Program class to the Validate method of the GenerateCommand class. This ensures that analytics will only be configured if the 'NoLogging' setting is not active, optimizing performance and improving the user's control over logging.
Adjusted the way the support key is handled when the logging is disabled. Previously, the support key wasn't printed at all if the logging was off. A message specifying that the support key is unavailable when logging is disabled is printed instead. This serves to ensure that users are informed about the unavailability of the support key when logging is off rather than silently omitting it.
=> Disable support keys if --no-logging is specified

test/ConsoleApp/ConsoleApp.sln, test/ConsoleApp/Net8/Net8.csproj, test/smoke-tests.ps1
The changes update the local smoke tests script to only build once with the `PublishReadyToRun` option enabled. This gives a 200% speed increase in running the local smoke test scripts
Tested on a 32-core AMD Threadripper with 128 GB of RAM workstation running Windows 10 on an NVMe drive
=> Speed up local smoke tests

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, README.md, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfacesByTag.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs, src/Refitter.Tests/Examples/MultipleInterfacesByEndpointTests.cs, src/Refitter.Tests/Examples/MultipleInterfacesByTagsTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/README.md
Generated interfaces across the codebase were changed from regular to partial. This change allows the clients to extend the functionality of these interfaces without modifying auto-generated code. Tests were also updated to verify this change
=> Generate Refit interfaces as partial

src/Refitter/GenerateCommand.cs, src/Refitter/Settings.cs, test/petstore.refitter, test/smoke-tests.ps1
The changes here gives users the choice to specify the path or URL to the OpenAPI specifications document from either the command line argument or via the settings file specified via `--settings-file`
This implements #149
=> Optional OpenAPI Path in CLI arguments

CHANGELOG.md, src/Refitter.Core/RefitGeneratorSettings.cs, src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/GenerateCommand.cs, src/Refitter/Program.cs, src/Refitter/README.md, src/Refitter/Settings.cs
--operation-name-template 
Generate operation names using pattern like '{operationName}Async' 
very simple pattern substitution.
I want to replace nswag with refitter in my codebase and I have so(ooo) many operations already generated with "Async" appended at the end (NSwag generator do this by default, to change the behaviour the template must be edited)
=> Introduce `--operation-name-template` command line argument

README.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter.Core/Settings/CodeGeneratorSettings.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.SourceGenerator/README.md, src/Refitter/README.md
The namespace setting in `codeGeneratorSettings` and related documentation was removed. This setting is a duplicated and was never respected, it was just causing confusion and was deemed unnecessary. The `namespace` property is already defined in `RefitGeneratorSettings` and from the CLI argument `--namespace`
This resolves the recent issue mentioned in #186 reported by @alrz
=> Remove `namespace` settings from `codeGeneratorSettings`

.github/workflows/qodana.yml
Added a new GitHub Actions workflow for running Qodana, a JetBrains code quality tool, on every push and pull request to the main branch. This workflow runs Qodana Scan on an ubuntu-latest runner and uses QODANA_TOKEN for authentication. It is necessary to maintain the code quality and ensure standards are met before merging into main branch.
=> Add JetBrains Qodana GitHub workflow

.github/workflows/qodana.yml, qodana.yml, src/qodana.yml
The changes here allows JetBrains Qodana to create pull requests with fixes for code analysis results
=> Enable JetBrains Qodana auto-fixes

src/Refitter.Core/RefitGenerator.cs, src/Refitter.Core/SchemaCleaner.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Tests/Examples/KeepSchemaPatternsTests.cs, src/Refitter.Tests/Examples/TrimUnusedSchemaTests.cs, src/Refitter/GenerateCommand.cs, src/Refitter/README.md, src/Refitter/Settings.cs
fixes #170 
This **DRAFT** implements the aforementioned feature request.
it adds a new commandline switch (`--trim-unused-schema`) aswell as configuration option (`trimUnusedSchema: true`) which works well in conjunction with `--tag Xyz` filters or similar.
The new option removes any Schema found in `#/components/...` which is not referenced in any way by the operations of the OpenApi document.
This results in much less code being generated for large documents which are filtered to generate only a few endpoints.
=> Remove unreferenced schema, add `--trim-unused-schema` & `--keep-schema`

README.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter.SourceGenerator/README.md, src/Refitter/Program.cs, src/Refitter/README.md
The changes here align the README files and update the DocFX articles with basic information about trimming unused schemas, a feature that was introduced by @kirides in #199
=> Update docs on trimming unused schemas

src/Refitter.Core/DependencyInjectionGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs
This allows for passing in a parameter of type Action\<IHttpClientBuilder\> when configuring the Refit client. This can be useful in scenarios where the consumer wants to modify the IHttpClientBuilder.
=> Add Action<IHttpClientBuilder>? parameter in ConfigureRefitClients

src/Refitter.Core/IdentifierUtils.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs
Added InterfaceName to avoid counting in operation names with parameter "multipleInterfaces". This solves a problem on apis with many tags with same operations.
=> Added InterfaceName to avoid counting in operation names

src/Refitter.Core/OperationNameGenerator.cs, src/Refitter.Core/RefitGenerator.cs, src/Refitter.Core/StringCasingExtensions.cs, src/Refitter.Tests/Examples/ColonsInPathTests.cs, src/Refitter.Tests/StringCasingExtensionTests.cs
This resolves #225 reported by @safakkesikci regarding OpenAPI specifications where paths include colons resulting in the generated code not being able to build
[customer.json](https://github.com/christianhelle/refitter/files/13431924/customer.json)
```json
{
"openApiPath": "./customer.json",
"namespace": "Customer",
"naming": {
"useOpenApiTitle": false
},
"multipleInterfaces": "ByTag",
"operationNameTemplate": "{operationName}Async",
"outputFolder": "Generated",
"outputFilename": "Customer.cs",
"codeGeneratorSettings": {
"requiredPropertiesMustBeDefined": true,
"generateDataAnnotations": true,
"anyType": "object",
"dateType": "System.DateTimeOffset",
"dateTimeType": "System.DateTimeOffset",
"timeType": "System.TimeSpan",
"timeSpanType": "System.TimeSpan",
"arrayType": …
```
=> Handle paths that contain colons

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Tests/Examples/NoContentApiResponseTests.cs
Updated logic to wrap void return types in `Task<ApiResponse>` when `settings.ReturnIApiResponse` is true.
=> Ensure Task<ApiResponse> is Returned for Void Methods in Generator

test/MauiExample/Platforms/Android/AndroidManifest.xml
The android:allowBackup attribute in the AndroidManifest.xml file for the MauiExample app has been updated. It was previously set to true, which allowed the Android system to backup app data. Now, it's been changed to false, effectively disabling the data backup feature for this application.
=> Disable app data backup in AndroidManifest.xml for example MAUI app

README.md, src/Refitter/GenerateCommand.cs, src/Refitter/README.md, src/Refitter/Settings.cs
This introduces a tin can donation banner at the end after successfully generating the code
The banner looks like this:
```
###################################################################
###################################################################
```
and can be suppressed by passing the `--no-banner` CLI tool argument
=> Add donation banner for Github Sponsors and buymeacoffee.com

src/Refitter/GenerateCommand.cs
Added lines to the exception handling code that create a console output encouraging users to report unresolved issues. The output includes a link to the project issues page on GitHub for ease of access and visibility.
=> Show error reporting suggestion banner upon error

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Tests/Examples/ArrayTypeReturnMultipleInterfacesByEndpointTests.cs, src/Refitter.Tests/Examples/ArrayTypeReturnMultipleInterfacesByTagTests.cs, src/Refitter.Tests/Examples/ArrayTypeReturnTests.cs
=> Fix issue where codeGeneratorSettings arrayType setting is not respected in Refit interface

.github/workflows/smoke-tests.yml, .github/workflows/template.yml, src/Refitter/GenerateCommand.cs, src/Refitter/Merger/OpenApiMerger.cs, src/Refitter/Merger/OpenApiMissingReferenceVisitor.cs, src/Refitter/Merger/OpenApiReferenceResolverVisitor.cs, src/Refitter/Merger/ReferenceCache.cs, src/Refitter/OAS/OpenApiReader.cs, src/Refitter/Refitter.csproj, src/Refitter/Validation/OpenApiValidator.cs, test/OpenAPI/v3.0/bot.components.yaml, test/OpenAPI/v3.0/bot.paths.yaml, test/smoke-tests.ps1
This resolves #192 
```
refitter openapi.yaml
...
OpenAPI specifications contains external references.                  
Attempting to merge of all external references into single document...
components.yaml - Paths must be a map/object
components.yaml - The field 'paths' in 'document' object is REQUIRED.
OpenAPI statistics:  
- Path Items: 32    
- Operations: 46    
- Parameters: 13    
- Request Bodies: 21
- Responses: 46     
- Links: 0          
- Callbacks: 0      
- Schemas: 210
Length: 90275 bytes
Output: C:\projects\christianhelle\refitter\src\Refitter\bin\Release\net8.0\Output.cs
Duration: 00:00:02.5172435
```
Currently, it supports having external references to files within the same folder, or remotely. But it won't work if the remote file has local external references. 
These …
=> Add support for OAS files with external references

src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs
This pull request implements the CustomCSharpPropertyNameGenerator class, which is used to generate property names in C# code based on a given JsonSchemaProperty. The implementation includes handling reserved characters and converting the property names to upper camel case. This implementation is taken directly from v14.0.0 of NSwag where it has changed the class accessibility to be `sealed`
This change is a prerequisite for upgrading to NSwag v14.0.0
=> Implement CustomCSharpPropertyNameGenerator 

README.md, docs/docfx_project/articles/cli-tool.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter/README.md, src/Refitter/Settings.cs
This pull request updates the documentation for the operation name generator options in the README file. It adds a link to the OperationNameGeneratorTypes documentation for more information. Additionally, it includes a fix for a broken link in the usage instructions.
=> Update --operation-name-generator options documentation

README.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter/README.md
This pull request adds documentation for the new options `generateDefaultAdditionalProperties` and `operationNameGenerator` to the .refitter file format. These options allow users to customize the behavior of the Refit library. The documentation includes descriptions of each option and their default values, as well as links to additional resources for more information.
=> Add new options to .refitter file format docs

src/Refitter.Core/Settings/RefitGeneratorSettings.cs, test/petstore.refitter
This pull request adds the `[JsonConverter(typeof(JsonStringEnumConverter))]` attribute to the `OperationNameGenerator` property in the `RefitGeneratorSettings` class. 
Additionally, it sets the `operationNameGenerator` property to `Default` in the petstore.refitter file.
This resolves #277
=> Serialize OperationNameGenerator enum as string

.github/workflows/regression-tests.yml, .github/workflows/smoke-tests.yml, README.md, docs/docfx_project/articles/cli-tool.md, src/Refitter/README.md, src/Refitter/Refitter.csproj
This resolves #290 and unblocks @yadanilov19
=> Add support for multiple target frameworks

src/Refitter.Core/ParameterExtractor.cs
hi ,
its a basic fix for issue #231.
AliasAs attribute should inside square brackets if it is a single attribute.
before fix : 
after fix :
=> fix: AliasAs attribute generation for StreamPart type

src/Refitter.Core/DependencyInjectionGenerator.cs, src/Refitter.Core/Settings/DependencyInjectionSettings.cs
Added a new **DependencyInjectionSettings** Property **ExtensionMethodName** with DefaultValue **ConfigureRefitClients**.
It can be set if you want to have control over the IServiceCollection Extension Method Name, or if you have multiple generated Client Api's with Dependency Injection support. Then the Extension Method will conflict.
Fixes #294
=> Added Optional Setting to name the IServiceCollection Extension Method

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs
This pull request fixes the issue where nullable types were being returned from the Refit interface when the setting `generateNullableReferenceTypes` is enabled. 
This also adds tests for generating code with non-nullable return types and includes an assert for nullable return type tests. 
Additionally, it updates the code to generate non-nullable return types in the ApiResponse.
This resolves #302
=> Fix response type always nullable under `generateNullableReferenceTypes`

src/Refitter.Core/README.md
=> chore: fix typo

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitInterfaceImports.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/GenerateCommand.cs, src/Refitter/Settings.cs
Refit supports also IObservable reactive response type in interfaces so I added this feature to Refitter because it was missing. 
I added property ReturnIApiResponse to Settings and RefitGeneratorSettings
It replaces System.Threading.Task import by System.Reactive and it generates IObservable<Unit> instead of Task and IObservable<> instead of Task<>. 
I added one unit test to test generated output is compilable. I had to add Unit class manually to mock missing System.Reactive.Unit class.
=> Generating IObservable type response

src/Refitter.Core/XmlDocumentationGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfacesByTag.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreOptionalParameters.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterface.g.cs, src/Refitter.SourceGenerator.Tests/CustomGenerated/CustomGenerated.cs, src/Refitter.Tests/XmlDocumentationGeneratorTests.cs
- Use the [recommended tag](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#document-members) "exception" instead of "throws"
- Format response status code list as a `<list type="table">`
Both of these somewhat improve the rendering of the generated comments in Visual Studio and Rider.
Before (Rider):
After (Rider):
Before (Visual Studio):
After (Visual Studio):
The generated code is a little uglier due to the flat nested XML. One could avoid this by refactoring the string builder utility methods.
=> Tweak xml docs

src/Refitter.Core/CSharpClientGeneratorFactory.cs, src/Refitter.Tests/CustomCSharpGeneratorSettingsTests.cs
Fixes #334.  
@christianhelle , I wasn't sure why only string/bool properties are mapped into NSwag.  I added a new check to ensure property types are compatible in hope this may mitigate the problem you were trying to avoid.
=> Fix code generator settings that are not of type string/bool

src/Refitter.Core/SchemaCleaner.cs, src/Refitter.Tests/Examples/TrimUnusedSchemaTests.cs
This PR fixes #352 by including the `schema.Item`-Schema for 'array'-type Schema
=> fixes #352: Collection-Type item schema was not kept

src/Refitter/GenerateCommand.cs
This pull request enhances error handling in the `GenerateCommand` class by providing more informative and visually distinct error messages to the console.
The `catch` block in the `GenerateCommand` class has been updated to improve error message visibility and information.
- In `GenerateCommand` class, a new variable `originalColor` is declared to store the current console color.
- The console color is then changed based on the `color` variable value.
- An error message, including the `label` and `error`, is written to the console.
- The console color is reset to the original color after the error message is displayed.
=> Fix missing OpenAPI validation result output

src/Refitter.Core/Serializer.cs
This pull request updates the `Serializer.cs` file to include the ability to write indented JSON. It also adds optional custom serialization options to the `Deserialize` and `Serialize` methods. This allows for more flexibility in the serialization process.
This resolves #383
=> Update Serializer to write indented JSON

src/Refitter.Core/Settings/DependencyInjectionSettings.cs, src/Refitter/GenerateCommand.cs, src/Refitter/SettingsValidator.cs
This pull request updates the `UsePolly` property in the `DependencyInjectionSettings` class to be a calculated property that reads/writes the `TransientErrorHandler` property. Additionally, it updates the `PollyMaxRetryCount` property to be a calculated property that updates the `MaxRetryCount` property. The `UsePolly` property is deprecated and a deprecation warning is shown. The pull request also includes a warning banner at the end of the execution.
=> UsePolly deprecation warning banner

src/Refitter.Core/CSharpClientGeneratorFactory.cs, src/Refitter.Tests/CustomCSharpGeneratorSettingsTests.cs, test/MauiExample/petstore.refitter, test/MinimalApi/petstore.refitter, test/petstore.refitter
This implements #407
This pull request updates the `CSharpClientGeneratorFactory` to use `CSharpClassStyle.Record` when the `GenerateNativeRecords` setting is true. This change adds proper support for generating contracts as immutable records
Here's an example of a generated immutable record using the changes in this pull request
```csharp
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
public partial record Tag
{
[JsonConstructor]
public Tag(long @id, string @name)
{
this.Id = @id;
this.Name = @name;
}
[JsonPropertyName("id")]
public long Id { get; init; }
[JsonPropertyName("name")]
public string Name { get; init; }
private IDictionary<string, object> _additionalProperties;
[JsonExtensionData]
public …
```
=> Add support for generating immutable records

src/Refitter.Core/DependencyInjectionGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithHttpResilience.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithPolly.g.cs, src/Refitter.Tests/DependencyInjectionGeneratorWithMicrosoftHttpResilienceTests.cs, src/Refitter.Tests/DependencyInjectionGeneratorWithPollyTests.cs
This pull request adds support for optional `RefitterSettings` in the generated IoC registration code. Previously, the generated code only supported basic configuration options. With this change, developers can now pass in a `RefitterSettings` object to customize the behavior of the generated code. This provides more flexibility and control over the generated code.
With these changes, the following `.refitter` settings file:
```json
{
"openApiPath": "../OpenAPI/v3.0/petstore.json",
"namespace": "Petstore",
"dependencyInjectionSettings": {
"baseUrl": "https://petstore3.swagger.io/api/v3",
"httpMessageHandlers": [ "TelemetryDelegatingHandler" ],
"transientErrorHandler": "Polly",
"maxRetryCount": 3,
"firstBackoffRetryInSeconds": 0.5
}
}
```
now generates:
```csharp
public static …
```
=> Add optional RefitterSettings in generated IoC registration code

README.md, docs/docfx_project/articles/using-the-generated-code.md, src/Refitter/README.md, test/MinimalApi/Program.cs
This pull request includes updates to the MinimalApi example and adds a new section to the documentation that explains how to use Dependency Injection with Refit. The changes ensure the code is current and provide clear instructions for configuring Refit interfaces using the `IServiceCollection` extension method `ConfigureRefitClients()`. This method allows for convenient configuration of multiple interfaces and supports features such as base URL, HTTP message handlers, transient error handling, and retry policies.
=> Add Dependency Injection section to docs

src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj, test/SourceGenerator/Directory.Build.props
This pull request reverts the version of Microsoft.CodeAnalysis.CSharp back to v4.8.0 and updates the SourceGenerator smoke test project to use v1.1.1. The previous version of Microsoft.CodeAnalysis.CSharp was causing compatibility issues, so it was necessary to revert it. Additionally, the SourceGenerator smoke test project needed to be updated to ensure compatibility with the new version.
=> Revert Microsoft.CodeAnalysis.CSharp to v4.8.0 and update SourceGenerator smoke test project to use v1.1.1

src/Refitter/Analytics.cs, src/Refitter/GenerateCommand.cs
This pull request improves the telemetry for the usage of the `--settings-file` option. Previously, only the `settings-file` object was logged, but now the `RefitGeneratorSettings` object is also logged when the `SettingsFilePath` is not null. This provides more detailed information for analysis.
=> Improve telemetry for --settings-file usage

src/Refitter/GenerateCommand.cs, src/Refitter/Settings.cs
That was the missing part of the #404 puzzle.
Previous #428 PR focused on generating things from a .refitter settings file. 
Now with that PR we can generate Apizr formatted Refit interfaces without settings file but with such a command line:
```shell
refitter https://petstore3.swagger.io/api/v3/openapi.yaml --use-apizr
```
It will generate the Refit interface, but formatted to Apizr by:
- Adding a final IApizrRequestOptions options parameter to all generated methods
- Providing cancellation tokens by Apizr request options instead of a dedicated parameter
- Using method overloads instead of optional parameters
So now we should get best of both CLI & SourceGenerator worlds 🥂
=> [Apizr] Generate Apizr formatted Refit interface without .refitter settings file

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Core/XmlDocumentationGenerator.cs, src/Refitter.Tests/XmlDocumentationGeneratorTests.cs
I just added the missing xml doc param over interface methods when needed:
```xml
/// <param name="options">The <see cref=\"IApizrRequestOptions\"/> instance to pass through the request.</param>
```
Added a test to cover it to.
=> [Apizr] Including an xml doc param for ApizrRequestOptions parameter

README.md, docs/docfx_project/articles/cli-tool.md, docs/docfx_project/articles/examples.md, docs/docfx_project/articles/refitter-file-format.md, docs/docfx_project/articles/source-generator.md, docs/docfx_project/articles/using-the-generated-code.md, docs/docfx_project/index.md, src/Refitter.SourceGenerator/README.md, src/Refitter/README.md
And finaly, here we are, the docs update final PR :)
Well that one is quite subjective as it depends on what you want to say, where and how.
Also, I'm french, so it may bring some english typos.
Feel free to fix it or ask me to or rephrase everything ^^
Jeremy
=> [Apizr] Docs updated about Apizr integration

src/Refitter.Core/RefitGenerator.cs
This pull request enables nullable annotations in the code and removes explicit disable warnings. The change is replacing `#nullable enable` with `#nullable enable annotations` to the generated code
This resolves #451 (discussed in #449)
=> Enable nullable annotations and disable warnings

src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs, src/Refitter.Tests/Examples/PercentageCharacterTests.cs
The CustomCSharpPropertyNameGenerator class was updated to replace the '%' character with 'Percent'. This fixes an issue where the generator was not correctly handling properties with '%' in their names.
This resolves #453
=> Handle '%' in property names

src/Refitter.Core/Templates/Class.liquid, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UsePolymorphicSerialization.g.cs, src/Refitter.Tests/Examples/UsePolymorphicSerializationTests.cs
I forgot attribute option ```IgnoreUnrecognizedTypeDiscriminators = true```
otherwise the fallback to base class is still not working ...
fix upon #462
=> added IgnoreUnrecognizedTypeDiscriminators = true

README.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter/README.md, src/Refitter/Settings.cs
This pull request updates the CLI option descriptions for `--use-polymorphic-serialization`, `--use-dynamic-querystring-parameters`, and `--use-apizr` in the README file. It also updates the file format documentation for the `.refitter` file to include the `usePolymorphicSerialization` option. These changes improve the clarity and accuracy of the CLI options and file format documentation for Refitter.
=> Add basic documentation for Polymorphic Serialization

src/Refitter/Analytics.cs, src/Refitter/Refitter.csproj, src/Refitter/SupportKeyInitializer.cs
This pull request adds telemetry logging to both Exceptionless and App Insights. 
It includes a new package reference to Microsoft.ApplicationInsights.WindowsServer and modifies the Analytics class to configure and log telemetry using the TelemetryClient. The LogFeatureUsage method has been updated to log feature usage to both Exceptionless and App Insights.
Additionally, a new SupportKeyInitializer class has been added to initialize the support key property in telemetry.
=> Use Azure App Insights for telemetry

src/Refitter.Tests/Build/ProjectFileContents.cs, test/Apizr/Sample.csproj
This pull request updates several package references in two project files to newer versions. The changes ensure that the projects use the latest stable versions of the Apizr integrations and extensions.
Package reference updates:
* [`src/Refitter.Tests/Build/ProjectFileContents.cs`](diffhunk://#diff-b50eea9ef8bc22e552467f370a0388c3036d02b4d024b5b854a6cd0dff53db01L19-R25): Updated multiple `Apizr` package references from version `6.0.0-preview.7` to `6.1.0`.
* [`test/Apizr/Sample.csproj`](diffhunk://#diff-fbb979c250529437fcdc9df15da6acf7b63a92ecf800d0daac71981fc28f0821L11-R14): Updated multiple `Apizr` package references from version `6.0.0` to `6.1.0`.
=> Update Apizr Dependencies to v6.1.0

src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Tests/Examples/ApizrTests.cs
As (self-)suggested in my [comment](https://github.com/christianhelle/refitter/issues/448#issuecomment-2320337815), here is the PR extending #417 that includes required query params into dynamic query parameter's constructor, when UseDynamicQuerystringParameters option is enabled.
Test updated.
Doc not updated but I don't think we have something to say into it about that, as asking for something mandatory seems obvious to me :)
=> [Query] Required query params must be initialized from constructor

src/Refitter.Core/CSharpClientGeneratorFactory.cs, src/Refitter.Core/Settings/CodeGeneratorSettings.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Tests/SerializerTests.cs
This PR adds the option to add another PropertyNameGenerator or ParameterNameGenerator.
References https://github.com/christianhelle/refitter/issues/516
These generators will not be serialized into the `.Refitter` configuration file.
```
return new RefitGeneratorSettings
{
CodeGeneratorSettings = new CodeGeneratorSettings
{
PropertyNameGenerator = new PascalCasePropertyNameGenerator()
},
ParameterNameGenerator = new CamelCaseParameterNameGenerator(),
```
//cc @christianerbsmehl
=> added options for a custom Name Generators

src/Refitter.Core/ApizrRegistrationGenerator.cs, src/Refitter.Core/Settings/ApizrPackages.cs, src/Refitter.Core/Settings/ApizrSettings.cs, src/Refitter.SourceGenerator/README.md, src/Refitter.Tests/ApizrGeneratorWithMicrosoftHttpResilienceTests.cs, src/Refitter.Tests/ApizrGeneratorWithPollyTests.cs, src/Refitter.Tests/Build/ProjectFileContents.cs, src/Refitter.Tests/SwaggerPetstoreApizrTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs, src/Refitter/README.md
I just removed the now deprecated Apizr.Integrations.Optional package from generating code and documentation. Optional monad pattern wasn't used that much, complicated to understand and refreneced Optional.Async package was no longer maintained for years now.
I's a breaking change for those who are using Refitter with "WithOptionalMediation" but they still can reference the deprecated integration package manually. Like I said, I bet almost no body use it actually.
I updated the doc of course and the tests.
I upgraded build test referenced packages too.
=> [Apizr] Deprecated Optional package removed from code & doc

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitInterfaceImports.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs
This PR adds the option to add inheritance from IDisposable by client interfaces.
Inheritance from IDisposable support add in Refit v8.0.0 https://github.com/reactiveui/refit/blob/8.0.0/InterfaceStubGenerator.Shared/Emitter.cs#L239
=> Clients implementing IDisposable interface

src/Refitter.MSBuild/Refitter.MSBuild.targets, src/Refitter.MSBuild/RefitterGenerateTask.cs, test/MSBuild/Refitter.MSBuild.Tests.csproj
This pull request introduces a new feature to disable logging in the `RefitterGenerateTask` and updates the related MSBuild targets and tests accordingly. The most important changes include adding a new property to control logging, modifying the MSBuild targets to use this property, and updating the process execution logic to respect this setting.
* [`src/Refitter.MSBuild/Refitter.MSBuild.targets`](diffhunk://#diff-d196700fc0243c6c2f10cef734033c77a5c72403b86c506f903bf3a3847be38fL4-R5): Added the `DisableLogging` attribute to the `RefitterGenerateTask` to allow disabling logging during the build process.
* [`src/Refitter.MSBuild/RefitterGenerateTask.cs`](diffhunk://#diff-25622107c893a8ef0e23ec6525c89d39133dd8741cc4480a898a77a1df53d488R11-R12): Introduced a new `DisableLogging` property in …
=> Add support for disabling telemetry from MSBuild task

README.md, docs/docfx_project/articles/msbuild.md, docs/docfx_project/articles/refitter-file-format.md, docs/docfx_project/articles/toc.yml, src/Refitter.MSBuild/README.md
This pull request includes updates to the documentation and examples for using Refitter, including new sections on using MSBuild tasks and clarifications on deprecated settings.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L312-R312): Updated the description of the `usePolly` setting to indicate it is deprecated and to use `transientErrorHandler` instead.
* [`docs/docfx_project/articles/refitter-file-format.md`](diffhunk://#diff-5700d0e2a30b141a3d7feeb8e6259a6553e4a0d884d6bab9c7fe16bbfbc3bc54L163-R163): Clarified that the `usePolly` setting is deprecated and should be replaced with `transientErrorHandler`.
* [`docs/docfx_project/articles/toc.yml`](diffhunk://#diff-083886ab0c6564e4e426fc7662dd7ff70aea18db9d70c1f58012 …
=> MSBuild Documentation

test/OpenAPI/v3.0/weather.json, test/smoke-tests.ps1
The actual change is from #556 which was implemented in [this pull request](https://github.com/christianhelle/oasreader/pull/71). The changes here just update the tests to include the example OpenAPI specification provided in #551 
This resolves #551
=> Less strict OpenAPI Validation rules

src/Refitter/GenerateCommand.cs, test/smoke-tests.ps1
This pull request includes changes to the `src/Refitter/GenerateCommand.cs` file to handle version flag arguments. The most important changes are:
* Added a check in the `Validate` method to return success if the version flag (`--version` or `-v`) is present in the command context arguments.
* Added a check in the `ExecuteAsync` method to return a status code of 0 if the version flag (`--version` or `-v`) is present in the command context arguments.
This resolves #560
=> Fix -v|--version CLI tool argument

src/Refitter.Core/IdentifierUtils.cs, src/Refitter.Tests/Examples/OperationIdWithInvalidFirstCharTests.cs
---
name: Pull request
title: 'Added simple logic to make most identifier strings valid'
labels: bug fix
assignees: Fargekritt
---
Adds an _ to operationIds that don´t have a valid first char to make safe identifier names
This approach is not perfect and have some flaws but will cover most normal cases. `operationId: "return"` should `@` instead of `_`but both works
[official Identifier-name naming rules](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names)
[Code Generator creates unsafe interface method names #360](https://github.com/christianhelle/refitter/issues/360)
=> Added simple logic to make most identifier strings valid

src/Refitter/Analytics.cs, src/Refitter/GenerateCommand.cs
Due to the popularity of Refitter, I reach my monthly cap on Exceptionless after just a few days into the month. Exceptionless was kind enough to sponsor me with 15k events a month, which was fine when Refitter was initially released but now, Refitter has 150k weekly usages which is way above the 15k monthly cap.
This pull request includes changes to the `src/Refitter/Analytics.cs` and `src/Refitter/GenerateCommand.cs` files to improve the logging mechanism by removing asynchronous calls and simplifying the code. The most important changes are summarized below:
* Changed the `LogFeatureUsage` method from `Task` to `void` and removed the asynchronous call to `ExceptionlessClient.Default.ProcessQueueAsync` in `src/Refitter/Analytics.cs`. …
=> Limit Exceptionless telemetry

src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
This resolves #568 which relates to #534
This pull request includes several changes to the `RefitterSourceGenerator.cs` file to improve error handling and diagnostics during the code generation process. The most important changes include adding a diagnostics parameter to the `TryDeserialize` method and enhancing the error handling mechanism.
Improvements to error handling and diagnostics:
* [`src/Refitter.SourceGenerator/RefitterSourceGenerator.cs`](diffhunk://#diff-90a29fe1932e165fb8390fa7a09adab7593510586be65b64abcdbfe46777758fL79-R79): Added a `diagnostics` parameter to the `TryDeserialize` method to collect diagnostics information. [[1]](diffhunk://#diff-90a29fe1932e165fb8390fa7a09adab7593510586be65b64abcdbfe46777758fL79-R79) …
=> Show Deserializaton Errors from Source Generator

src/Refitter.Core/Templates/JsonInheritanceConverter.liquid
Fixes `StackOverflowException` which is thrown when subtype discriminator value is unknown.
The same issue was reported in [NJsonSchema](https://github.com/RicoSuter/NJsonSchema/issues/1728) with a corresponding [fix](https://github.com/RicoSuter/NJsonSchema/pull/1729).
=> Return null when object subtype is not found

src/Refitter.SourceGenerator.Tests/Refitter.SourceGenerator.Tests.csproj
Reverts christianhelle/refitter#586
=> Revert "chore(deps): update dependency fluentassertions to v8"

src/Refitter.Core/RefitGenerator.cs, src/Refitter.Core/SchemaCleaner.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Tests/Examples/IncludeInheritanceHierarchyTests.cs, src/Refitter/GenerateCommand.cs, src/Refitter/Settings.cs
This PR solves #557 by providing a flag to either keep all possible union types/the whole inheritance chain of an abstract type, or trimming the schema to remove any "Anonymous" types
=> - #557 - discard unused union types/inheritance types via config

README.md, docs/docfx_project/articles/cli-tool.md, docs/docfx_project/articles/refitter-file-format.md, src/Refitter/README.md
Adds missing documentation updates for changes introduced in #575
This pull request adds a new option to include inheritance hierarchy in various configuration files and documentation. The main changes involve updating the `README.md` and other documentation files to reflect this new option.
Updates to documentation and configuration:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R101): Added the `--include-inheritance-hierarchy` option to the `OPTIONS:` section and described its functionality in the example `.refitter` file. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R101) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R215) …
=> Update docs for --include-inheritance-hierarchy

src/Refitter.Core/Refitter.Core.csproj
This pull request includes a small change to the `src/Refitter.Core/Refitter.Core.csproj` file. The change removes the `System.Text.Json` package reference.
* [`src/Refitter.Core/Refitter.Core.csproj`](diffhunk://#diff-444c79f78399cbb25d189742011c22f15d51330d014b91a714aabc678c422aa2L18): Removed the `System.Text.Json` package reference.
=> Remove dependency on System.Text.Json

src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Core/Settings/CodeGeneratorSettings.cs, src/Refitter.SourceGenerator/RefitterSourceGenerator.cs, src/Refitter.Tests/Examples/UseIsoDateFormatTests.cs, src/Refitter/GenerateCommand.cs
This should fix the #599 
This pull request includes several changes to improve the handling of date formats and enhance test coverage in the `Refitter` project. The most important changes include modifying the `CodeGeneratorSettings` class to support nullable date format strings, updating the `GetQueryAttribute` method to use the new date format property, and expanding the test suite to cover various scenarios related to date formats and settings.
Enhancements to date format handling:
* [`src/Refitter.Core/Settings/CodeGeneratorSettings.cs`](diffhunk://#diff-6ef4d463b40adb93fa8148a5aac284ac193b42d09a8c86af3e433d9a86cf405cL162-R165): Modified the `DateFormat` property to be nullable and added a summary comment.
* [`src/Refitter.Core/ParameterExtractor.cs`](diffhunk://#diff-fbf2584535de6a59 …
=> Fix ISO date format handling when dateFormat is defined in settings file

src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Core/Settings/CodeGeneratorSettings.cs, src/Refitter.Tests/Examples/UseIsoDateFormatTests.cs
This builds upon #603 and #599 
This pull request introduces several changes to enhance date and date-time formatting capabilities in the `Refitter.Core` project. The key updates include adding support for date-time string formats, modifying the `ParameterExtractor` to handle the new formats, and updating the related test cases to verify these changes.
Enhancements to date and date-time formatting:
* [`src/Refitter.Core/Settings/CodeGeneratorSettings.cs`](diffhunk://#diff-6ef4d463b40adb93fa8148a5aac284ac193b42d09a8c86af3e433d9a86cf405cR167-R171): Added a new property `DateTimeFormat` to the `CodeGeneratorSettings` class to allow specifying a custom date-time string format.
* [`src/Refitter.Core/ParameterExtractor.cs`](diffhunk://#diff-fbf2584535de6a59f14801ef402a25e5d27e497a7fbebd15c6d2052 …
=> Add support for custom DateTimeFormat

src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Core/XmlDocumentationGenerator.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfacesByTag.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreOptionalParameters.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithHttpResilience.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithPolly.g.cs, src/Refitter.SourceGenerator.Tests/CustomGenerated/CustomGenerated.cs, src/Refitter.SourceGenerator/Refitter.SourceGenerator.csproj, src/Refitter.Tests/Build/ProjectFileContents.cs, src/Refitter.Tests/Examples/SymbolsInDescriptionTests.cs, test/ConsoleApp/Directory.Build.props
This resolves #605 
This pull request introduces several changes aimed at improving XML documentation generation and ensuring that symbols in descriptions are properly escaped. Additionally, it includes updates to the project files to generate documentation files and adds new tests to verify these changes.
Improvements to XML documentation generation:
* [`src/Refitter.Core/XmlDocumentationGenerator.cs`](diffhunk://#diff-1cee808dcdf73b5cd2a273cb85f48e831c6d1bebfba1827469a394469113e5d3L58-R61): Added a new private method `EscapeSymbols` to properly escape `<` and `>` symbols in method summaries and remarks. Updated `AppendMethodDocumentation` to use `EscapeSymbols` for method summaries and remarks. [[1]](diffhunk://#diff-1cee808dcdf73b5cd2a273cb85f48e831c6d1bebfba1827469a394469113e5d3L58-R61 …
=> Fix invalid characters in generated XML docs

src/Refitter.Core/RefitInterfaceGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceByTagGenerator.cs, src/Refitter.Core/RefitMultipleInterfaceGenerator.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/Refitter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfaces.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreMultipleInterfacesByTag.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreOptionalParameters.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithHttpResilience.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/SwaggerPetstoreSingleInterfaceWithPolly.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UseJsonInheritanceConverter.g.cs, src/Refitter.SourceGenerator.Tests/AdditionalFiles/Generated/UsePolymorphicSerialization.g.cs, src/Refitter.SourceGenerator.Tests/CustomGenerated/CustomGenerated.cs, src/Refitter.Tests/Examples/RequestResponseHeadersTests.cs, src/Refitter.Tests/Examples/ResponseHeadersTests.cs, src/Refitter.Tests/SwaggerPetstoreApizrTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs
This resolves #617
This pull request includes several changes to enhance the header generation functionality in the `Refitter.Core` project. The key changes involve renaming methods to reflect their purpose better, adding support for generating `Content-Type` headers, and updating tests to verify the new functionality.
With the changes in the pull request, the following OpenAPI document:
```yaml
openapi: 3.0.1
paths:
/foo:
post:
requestBody:
content:
application/json:
schema:
type: string
required: true
responses:
'200':
content:
application/json:
schema:
type: string
```
Generate the following Refit interface:
```csharp
public partial interface IApiClient
{
[Headers("Accept: application/json", "Content-Type: application/json")]
[Post("/foo")]
Task<string> Foo([Body] string body);
}
```
* …
=> Fix missing Content-Type [Headers]

.github/workflows/build.yml, src/Makefile, src/Refitter.SourceGenerator/RefitterSourceGenerator.cs
This should resolve #627
The problem that the source generator occasionally fails to deserialize the `.refitter` file. When this happens, the problem is reported to Visual Studio as an `Error`, which causes Visual Studio to fail to build. The solution, which I hope is temporary, is to report the deserialization error with the severity level of `Info` so Visual Studio doesn't panic. Even though the source generator occasionally fails, it seems to work eventually. I haven't figured out exactly what I wrong yet and I wanted to go in the direction of just handling the deserialization myself, but that probably won't help since Refitter depends on NSwag, which also needs to deserialize the OpenAPI document. Maybe one day I'll nail this, but for now, this is blocking some users, and this "fix" …
=> Temporary fix for Source Generator when running in Visual Studio

src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs, src/Refitter.Tests/Examples/PercentageCharacterTests.cs, src/Refitter.Tests/Examples/UnderscoresToPascalCaseTests.cs
This resolves #641 
This pull request includes several changes to improve the handling of property names and add new tests for code generation. The most important changes include modifying the property name conversion method, updating an existing test to reflect the new naming convention, and adding a new test class to validate the handling of underscores in property names.
* [`src/Refitter.Core/CustomCSharpPropertyNameGenerator.cs`](diffhunk://#diff-3bc6e4e9dc096be77cc2b29bcaeac87b344b9452ac0adf4758567c1d3ef42676L45-R47): Modified the `ReplaceNameContainingReservedCharacters` method to include a new step that converts snake_case to PascalCase.
* [`src/Refitter.Tests/Examples/PercentageCharacterTests.cs`](diffhunk://#diff-f47993865e8ded0a978a4970a639bf8d3fe9dc8ce620481bd225933ddb601182L59- …
=> Convert properties with underscores to PascalCase

src/Refitter.Core/ParameterExtractor.cs, src/Refitter.Core/Settings/RefitGeneratorSettings.cs, src/Refitter.Tests/Resources/EmbeddedResources.cs, src/Refitter.Tests/Resources/SampleOpenSpecifications.cs, src/Refitter.Tests/Resources/V2/SwaggerPetstoreWithAuthenticationHeaders.json, src/Refitter.Tests/Resources/V2/SwaggerPetstoreWithAuthenticationHeaders.yaml, src/Refitter.Tests/Resources/V3/SwaggerPetstoreWithAuthenticationHeaders.json, src/Refitter.Tests/Resources/V3/SwaggerPetstoreWithAuthenticationHeaders.yaml, src/Refitter.Tests/SwaggerPetstoreApizrTests.cs, src/Refitter.Tests/SwaggerPetstoreTests.cs
Added generation of Header parameters for Security Schema present in schemas
=> Add Header Parameters for Security Schemes

.github/workflows/smoke-tests.yml, test/OpenAPI/v3.0/petstore.json, test/OpenAPI/v3.0/petstore.yaml, test/petstore.refitter
This pull request introduces changes to enhance the security configuration and authentication handling in the OpenAPI Petstore examples. The most important changes include adding security definitions for API key authentication and enabling the generation of authentication headers in the refitter configuration.
* [`test/OpenAPI/v3.0/petstore.json`](diffhunk://#diff-c55f880408eb644118b22e26e9ed4a87ac24e3a2facb3d82d9a09edc2f00cee7R42-R46): Added a `security` section specifying `api_key` as a required security scheme.
* [`test/OpenAPI/v3.0/petstore.yaml`](diffhunk://#diff-f77afc5897e8444172cd6887a297dd5b026880d961970bb71a2b9acc1319abbbR36-R37): Added a `security` section under `tags:` to include `api_key` as a security requirement.
* …
=> Update smoke tests to generate authentication headers

src/Refitter.Core/RefitInterfaceGenerator.cs
This address the issue pointed out by @pfeigl
This pull request simplifies the logic for determining the return type in the `GetTypeName` method of the `RefitInterfaceGenerator` class. The most important change focuses on narrowing the range of response codes considered when no explicit success codes are found.
* [`src/Refitter.Core/RefitInterfaceGenerator.cs`](diffhunk://#diff-95f8543dcf9e641fc59aef59be1a4b37089babe99947ddc943628852fdb0f6a8L118-R121): The logic for handling response codes was simplified by removing checks for multiple response code ranges (`1XX`, `3XX`, `4XX`, `5XX`) and focusing solely on the `2XX` range when no explicit success codes are found. This reduces unnecessary complexity in the code.…lution
=> Response type handling to only use 2XX range
